### ISSUE TITLE
So I broke the Internet, need help

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/Webmarks#14]
Hello guys, i somehow broke the internet. (hint: I uploaded a picture of Kim Kardashian)

**Comment by Protohedgehog** [comment]
Oh jolly bad show old chap

**Comment by oliversauter** [comment]
Thanks for your help @Protohedgehog! Well appreciated. But your "guest" wasn't cool enough. Sorry not sorry Kanye.

**Comment by Protohedgehog** [comment]
Does this mean we saved the internet..?
