### ISSUE TITLE
Deciding on an open source licence for Webmarks

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/Webmarks#16]
## Update:

After taking all the different views into account, it seems like the best choice is the BSD-2 Licence.

Why?

**1. It gives us more flexibility regarding the course of the project.**
Means: We will have no legal problems ourselves, IF we decide to add closed source components

**2. The GPL makes the implementation of this software in other software harder**
Means: We want our software to get used, wherever it makes sense.

### Original Post
Heyho people! 

What are the differences of having an rather restrictive licence as the GPL in comparison to a BSD licence, when it comes to:

1. The willingness of developers working on the project
2. Protection against the commercial use of the software in a direct competitive product?

Thanks for your input on this!

**Comment by RaoOfPhysics** [comment]
Not sure I can meaningfully contribute to this discussion other than by pointing to some resources:

- http://choosealicense.com/ in case you weren't aware of it
- https://www.gnu.org/philosophy/programs-must-not-limit-freedom-to-run.html
- https://www.gnu.org/licenses/license-compatibility.html
- http://dustycloud.org/blog/why-i-am-pro-gpl/
    - Summary: https://www.reddit.com/r/linux/comments/3e395n/why_i_am_progpl/ctb923f

**Comment by oliversauter** [comment]
Thanks Achintya for your input!

Some I already read, some are new :)

I haven't written out all my thoughts on this. I will come back to this within the next days and document all my thinking which went into this so far. Currently focussing to get the outreach for new developers effective.

**Comment by lwm** [comment]
Hey, just found this repo and sounds like fun. My two cents to the discussion ...

If you will be continuing this project as an official fork of the [hypothesis](https://github.com/hypothesis/h) project, then you must find a compatible license with [their license](https://github.com/hypothesis/h/blob/master/LICENSE) requirements. There seems to be sub licensed components also.

**Comment by oliversauter** [comment]
Hello Luke (@lwm) , thanks for joining in. :)

As I promised to @RaoOfPhysics, here is a sum-up of my thinking process:

So I had a chat with Richard yesterday, who got me a more insights about the licensing.
He was able to make me get rid of concerns about unwanted pirating, which helped me a lot to think more clearly about the matter.

**WHAT IS THE SITUATION?**
1. Hypothes.is is a BSD2 license, which would allow us to change the license when redistributing.
2. I believe in the open source thought and think that our software should remain open source in the process of being reused.
3. There might be some components of the WorldBrain software that will be closed source like algorithms.
This might be due to several circumstances. That some intellectual property stays within the Worldbrain project or to keep some mechanisms secret to prevent fraud on the software. 
This is just a thought and not a definite requirement yet. Still I believe this future option should be considered when choosing the appropriate license.
4. As far as I see, the subcomponents are all with the MIT license, which would allow the integration into a GPL license:
"The MIT license is also compatible with many copyleft licenses, such as the GPL; MIT licensed software can be integrated into GPL software, but not the other way around." (https://www.wikiwand.com/en/MIT_License)


**WHAT ARE THE OPTIONS?**
**GPL license:**
There should not be problem of the Webmarks software being reused by other entities, but if, then only if the code stays open source and not being closed up in proprietary software.

**BSD-2 Licence**
This would allow companies to use our software to integrate it into closed source environments. 
Is this what we want? If we produce the tool as open source, all its changes should stay open source as well, i guess.

[As others analysed](http://www.matusiak.eu/numerodix/blog/2007/12/15/gpl-vs-bsd-a-matter-of-sustainability/), the GPL might be a more sustainable choice for a license:
"BSD freedom, on the other hand, is "lossy". If I get BSD code I have a lot of freedom, but the next guy doesn't. It's fairly well known that there is BSD code in Windows. And obviously, whatever Microsoft did with that code, they have no obligation to release their changes. So the code *was* free at one point, but it didn't *remain* free. Furthermore, even if they didn't change it one bit, if the original author is no longer around, Microsoft is still sitting on BSD code that is free for *them*, but it's no longer free for anyone else."

**QUESTIONS**
1. Does using the GPL license limit our own use of the software in the future? Are we as developers of it also restricted in combining the software with closed source components?
2. [Another article](https://www.freebsd.org/doc/en/articles/bsdl-gpl/article.html) wrote about that this is the case for statically linked components and not with dynamically linked ones. This is a new concept for me, can someone explain to me what this means?

Thank you guys for your help!

**Comment by lwm** [comment]
First of all, [IANAL](http://en.wikipedia.org/wiki/IANAL) :+1: 

> Are we as developers of it also restricted in combining the software with closed source components?

This is probably related to the 'viral' aspect ([source](https://en.wikipedia.org/wiki/Viral_license)) of the GPL licenses. From this [FAQ section](https://www.gnu.org/licenses/gpl-faq.html#GPLModuleLicense) it appears that all components of the system must be GPL compatible.

> 2. Another article wrote about that this is the case for statically linked components and not with dynamically linked ones. This is a new concept for me, can someone explain to me what this means?

Not very useful for this one. This [SO answer](http://programmers.stackexchange.com/a/167781) seems to cover it though.

If considering using a GPL license, you probably want the [AGPL](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-%28agpl-3.0%29), as I believe the ASP loophole (see introduction of the [wikipedia page on the AGPL](https://en.wikipedia.org/wiki/Affero_General_Public_License)) in the GPL would apply to your service ? Not sure.

In any case, it's tricky stuff getting the license right. Maybe the [FSFE](https://fsfe.org/activities/ftf/index.en.html) could help? They are headquarter'd in Berlin, I think ...

**Comment by oliversauter** [comment]
Thanks Luke for your research.

After another few chats with experienced people here at the OK Lab, the focus was mainly on the BSD or MIT license, due to the given flexibility. 
A permissive license, like the BSD, would make sense, because at some point there could possibly be some closed source components of the whole software ecosystem as well. 
Choosing the GPL would probably unnecessarily complicate such a decision later.

At the beginning, I another reason for the thought about choosing the GPL were some worries about how easily the code can be used by other companies for commercial purposes to mimic the project somehow.
But thanks to the talk with Richard, I was able to overcome these worries. 

So the stance to this point is to use the BSD-3 license.

@lwm How about we meet up for a beer somewhat in the coming days to have chat? We are both in Berlin. :)

**Comment by lwm** [comment]
@oliversauter 
I meant to make it to that OK Lab meetup last night. 

Anyway, sure, drop me a line, my email is on my profile.
