### ISSUE TITLE
As a a user, I want to add a comment (with picture upload)

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/Webmarks#27]
## User Story:
As a User, I want to add images to my comments via Drag&Drop.

## Why?
Currently, I can only add images via a link in the mark-up text. This doesn't allow me to add individual pictures. It often brought me to the point of falsely dragging and dropping the picture and with that discarding my whole comment (because the picture loaded in the browser then)

## Details on Execution:
Here are two possibilities. Either we make a image upload via the markup editor possible or when somebody drags and drops a picture into the comment, we just save the link as reference. So it is a "semi" drag&drop. 

Also we could think of getting rid of the markup editor all together. It is a very bulky way of editing. Maybe some simplified WYSIWYG Editor, that allows picture upload anyway.

Is this an option?
https://mindmup.github.io/bootstrap-wysiwyg/

_Current way of saving a picture:_

in markup:
`![Image` Description](http://www.cmo.nl/vncanon/images/6-milieu/klimaat/klimaatverandering02.jpg)

## MOCKUPS:
https://drive.google.com/drive/u/0/folders/0BwhDeiu80lkjYmYycTlzTkExX0U

[--- This issue is linked with an Asana task
#url https://app.asana.com/0/0/82254329257804/f
---[aa]

**Comment by lwm** [comment]
I see they introduced the markdown editor with [#1479][1]. 

This was preceded by a WYSIWYG editor in [#1478][2] (which got rejected due to some offline discussion apparently). Perhaps we could resurrect the feature from [#1478][2] if it will cover comments / picture uploads.

I think we'd need to discuss with the hypothesis devs if we could get a license conflict ... 

[1]: https://github.com/hypothesis/h/pull/1479
[2]: https://github.com/hypothesis/h/pull/1478

**Comment by oliversauter** [comment]
Hey Luke, 

this is great news, thanks for investigating this. :)
It is so well described in this post why it makes sense to have a WYSIWYG editor.

Cool here: we can add with new use cases with our user base and also with a better option for an editor, since it is sleeker and completely open source.
https://mindmup.github.io/bootstrap-wysiwyg/

I will also write Jake Hartnell, who opened the issue.

**Besides that:**
In general a very good idea to look into the issues already existing and compare them with our features
That is a good next step to define the tasks well.
I will look into it the next 2 days.
A 2nd pair of eyes would be helpful though :)

Best,
Oliver
