### ISSUE TITLE
add trusted sources list

### ISSUE THREAD

**Issue by oliversauter** [WorldBrain/webmarks#30]
Add a separate page (needs an own url), with a list of domains that have been marked as trustworthy.
For that take all domains in table `domain_list` where  `trusted_source`=`true` and `indexed`=`true`

**Purpose:**
Google Custom Search allows to dynamically take all the links on a page we give it and limits the sources to that. We would link to our List of Trusted sources (on the right of the menu bar). Means, this page HAS to have a separate URL!

More information in the prototype [specifications](https://github.com/WorldBrain/START-HERE/wiki/Specifications-for-Search-Engine-Prototype#4-the-list-of-sources).

**Comment by Xantomen** [comment]
Hi there! Where's that table domain_list defined? Does it exist already? I'm trying to understand where things are and how they link together.

**Comment by oliversauter** [comment]
Hey Xantomen! 

Great to finally welcome you here :)
The whole specs are defined here: https://github.com/WorldBrain/START-HERE/wiki

But we just decided to postpone this feature in the prototype to keep our focus. It will come as soon as we can support our trusted sources with some data (coming from the interactions with the lists people create)

Will close it now.

**Comment by Xantomen** [comment]
ok,ok! thx!
