### ISSUE TITLE
As a developer, I want to fork hypothesis, sanely, for the greater good

### ISSUE THREAD

**Issue by lwm** [WorldBrain/Webmarks#32]
### Overview
As it has been communicated by @oliversauter, the first prototype will be only a number of changes to the [hypothesis/h][1] project. 

This means we need a plan for maintaining a fork of this project and being able to:
  - stay up to date with upstream hypothesis/h (fixes, features, etc.)
  - contribute our project specific changes in a compatible way

### Status
Right now, [WorldBrain/Webmarks][2] is an incompatible fork. We are 450 commits behind and there are many merge conflicts.

### Initial proposal
What I propose is the following:
  - revert [the 80 commits of @oliversauter][3].
  - get Worldbrain/Webmarks up to date with Hypothesis/h

We can take those 80 commits which seem to be documentation / cosmetic / no new functionality (am I correct?) and put them into a `webmarks-docs` folder which won't create conflicts. We then add a note in the hypothesis `README.rst` which says - this is a fork and we maintain our own readme in `webmark-docs/README.md`.

### Work flow proposal
I would propose that we:
  - prioritise, clearly, what are the features that need to be done for the MVP
  - take each one and propose them on the upstream hypothesis project (either [here][4] or [here][5])
  - begin to develop them on our own fork, regardless
  - if the feature is welcome to core devs of hypothesis, then it goes upstream
  - if not, we commit this to our fork in a future compatible way

@WorldBrain/dev-champs 

Thoughts?

[1]: https://github.com/hypothesis/h
[2]: https://github.com/WorldBrain/Webmarks
[3]: https://github.com/hypothesis/h/compare/master...WorldBrain:master
[4]: https://github.com/hypothesis/vision/issues/
[5]: https://github.com/hypothesis/h/issues

**Comment by lwm** [comment]
FYI - a possible alternative [is drawn crudely here][1]. 

However, I don't think that fits, at least for the prototype, since all changes could go straight into hypothesis.

[1]: https://i.imgur.com/Vvkodca.png

**Comment by lwm** [comment]
> Can you elaborate on it a little bit more? 

Well, with regard to the greater good - it would be Webmarks helping the world. And 'sanely' means having a fixed work flow for developing webmarks (as a fork of hypothesis) across a distributed team and surviving merge conflicts and losing changes or other nasty git stuff.

**Comment by oliversauter** [comment]
@lwm i explained what we aim for here to @geass. He will also join into the discussion on the infrastructure.

**Comment by lwm** [comment]
> He will also join into the discussion on the infrastructure. 

OK, let's continue the discussion there :+1:

**Comment by oliversauter** [comment]
I looked now over the issues here and compared them with the ones from hypothes.is.
https://github.com/hypothesis/vision

It's actually a nice idea to have all the feature requests separate. They are all collected in the "Vision" Repository.
Actually makes a lot of sense to decouple this. 

@mr-mig already mentioned that recently, but I had no time to do so yet.

**Comment by lwm** [comment]
Closing this now as we seem to be in agreement as how to proceed following the above ideas
