### ISSUE TITLE
Out-of-date Hypothesis docs hosted on RTD

### ISSUE THREAD

**Issue by nickstenning** [WorldBrain/Webmarks#39]
Hi folks,

Do you think we could do something about http://webmarks.readthedocs.io/en/latest/? It's a bit misleading to have out-of-date Hypothesis docs hanging around on a different domain.

**Comment by oliversauter** [comment]
Hey Nick,

Sure.I will remove it, we don't need it right now.
I've seen that you updated your documentation. Looks great!
